# STT Analytics Platform - Default Configuration
# Override with config/local.yml (gitignored)

paths:
  raw_dir: "data/raw"
  clean_dir: "data/clean"
  artifacts_dir: "artifacts"
  reports_dir: "artifacts/reports"
  charts_dir: "artifacts/charts"

parsing:
  # CSV format settings
  delimiter: ";"
  
  # Encoding detection (try in order)
  encodings_try:
    - "utf-8-sig"
    - "cp1250"
    - "latin-1"
  
  # Column renaming (map source column names to expected names)
  # Use this for non-English CSV files
  column_mapping:
    "Aktivity / Přepis hovoru / Aktivity": "call_id"
    "Aktivity / Přepis hovoru / Text": "text"
    "Aktivity / Přepis hovoru / Typ": "speaker"
    "Aktivity / Přepis hovoru / Začátek v": "start_time"
    "Aktivity / Přepis hovoru / Konec v": "end_time"
    "Směr": "direction"
    "Uživatel": "agent_name"
    "Číslo zákazníka": "customer_id"
    "Doba trvání": "call_duration"
  
  # Field mappings (customize per CSV format)
  call_id_field: "call_id"
  speaker_field: "speaker"
  text_field: "text"
  start_time_field: "start_time"
  end_time_field: "end_time"
  
  # Metadata fields (optional, extracted from first row)
  metadata_fields:
    - "call_id"
    - "call_start"
    - "call_duration"
    - "direction"
    - "agent_id"
    - "agent_name"
    - "customer_id"
    - "language"
  
  # Utterance fields (extracted from subsequent rows)
  utterance_fields:
    - "utterance_index"
    - "speaker"
    - "start_time"
    - "end_time"
    - "text"

validation:
  # Require call_id (if false, use filename as fallback)
  require_call_id: true
  
  # Flag utterances with invalid times (but don't reject)
  allow_invalid_timestamps: true
  
  # Flag negative durations
  allow_negative_durations: false
  
  # Flag unknown speakers
  allow_unknown_speakers: true

metrics:
  # Sweep-line precision (seconds)
  time_precision: 0.001
  
  # Word count regex pattern (Unicode-aware)
  word_pattern: "\\w+"
  
  # Gap threshold for "silence" classification (seconds)
  significant_gap_threshold: 0.5
  
  # Overlap threshold for "interruption" classification (seconds)
  interruption_threshold: 0.1

dashboard:
  # Default view on load
  default_view: "call"
  
  # Streamlit configuration
  page_title: "STT Analytics Platform"
  page_icon: "📊"
  layout: "wide"
  
  # Chart themes
  plotly_template: "plotly_white"
  color_scheme:
    AGENT: "#2E86AB"
    CUSTOMER: "#A23B72"
    OTHER: "#F18F01"
    UNKNOWN: "#C73E1D"
  
  # Export settings
  export_image_width: 1200
  export_image_height: 600
  export_image_format: "png"

report:
  # PDF generation settings
  page_size: "A4"
  orientation: "portrait"
  
  # Fonts (ReportLab built-in)
  title_font: "Helvetica-Bold"
  body_font: "Helvetica"
  mono_font: "Courier"
  
  # Chart embedding
  chart_dpi: 150
  chart_quality: 90

logging:
  # Loguru configuration
  level: "INFO"
  format: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan> - <level>{message}</level>"
  rotation: "10 MB"
  retention: "30 days"
  compression: "zip"

version:
  schema_version: "1.0.0"
  config_version: "1.0.0"
